[IV-24-25] Objetivo0
lmchaves/OrganizarTaller pull request #1
Opened 2024-09-26 07:28 UTC by lmchaves

[*] ¿Se trata de un problema real del que se tenga conocimiento personal?
 [*] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
[*] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
[*] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
[*] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?

2024-09-27 11:13 UTC, lmchaves commented
revisión @jj

2024-09-27 15:35 UTC, JJ requested changes
Por favor, comienza por enunciar el problema básico o los problemas del taller de coches en los que te vayas a centrar.

Como dice en el fichero de [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md):

> Si se describe lo que el cliente quiere hacer sin decir por qué quiere hacerlo, no estás describiendo el problema, estás describiendo una solución.

2024-09-27 15:35 UTC, JJ commented on README.md
> +Este proyecto está enfocado en desarrollar una aplicación para optimizar la gestión de un taller de coches. A través de la aplicación, se busca facilitar la planificación y control de tareas como la
Empezar por "una aplicación" no es un buen comienzo. Debes hablar de un problema.

2024-09-28 12:57 UTC, lmchaves commented
He realizado los cambios en la descripción del problema @JJ

2024-09-28 16:34 UTC, JJ requested changes
Si te has preguntado el por qué de este objetivo (que posiblemente deberías), no estamos midiendo tu capacidad de "generar" problemas, sino tu capacidad de identificar uno y describirlo con precisión en un documento para poder llevar a cabo un desarrollo en el marco de esta asignatura.

2024-09-28 16:34 UTC, JJ commented on README.md
> +2. Gestión ineficiente del inventario: Muchos talleres no tienen control automatizado de las piezas disponibles, lo que puede llevar a una escasez de piezas críticas o, por el contrario, a tener un e
Como dice en la [página de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#en-el-contenido), 

> Se trata de describir bien un problema, un solo problema, con una clientela claramente definida. En el momento que se diga "además" ya estás introduciendo otro problema (y por tanto, estás más lejos de alcanzar el objetivo).

2024-09-29 11:31 UTC, lmchaves commented
revisión @JJ

2024-09-30 05:39 UTC, JJ requested changes
Hemos pasado de un estado en el cual tenías varios problemas, cada uno de ellos más o menos bien enunciados, a un estado en el cual tienes los mismos problemas (con lo cual no has solucionado el comentario que se ha hecho, el que tengas varios problemas) pero ahora peor enunciados.
Va a ser complicado que se supere un objetivo sin dos condiciones fundamentales:
1. Que se entienda qué es lo que se busca en en ese objetivo y por qué (en este caso, describir un problema con el que se va a trbajar)
2. Que no se entienda la metodología que hay que aplicar; en este caso, *design thinking* en su primera fase, empatía. Aplicando esa metodología, mediante el juego o simplemente hablando con la persona que tiene el taller, se puede llegar a un estado en el cual se entienda el problema y se pueda empezar a solucionar.
Te rogaría que intentaras hacerlo así. En ingeniería se proporcionan estas metodologías para tratar de evitar bucles infinitos en los que se hacen nuevos intentos que siguen sin superar los requisitos en una fase determinada del proyecto, se rechazan porque no corresponden, y se tiene que comenzar de nuevo.

2024-09-30 05:39 UTC, JJ commented on README.md
> +Un taller de coches tiene un problema de organización que afecta el funcionamiento diario y la calidad del servicio ofrecido a los clientes. La falta de una estructura clara y eficiente en la gestión
¿De qué forma crees que esto enuncia de forma precisa un problema para poder trabajar como proyecto de la asignatura? ¿Crees que alguien va a tomar cosas como "control del inventario" y hacer un "control del inventario"? ¿Crees que eso es una enunciación precisa de un problema, y solo uno?

2024-09-30 05:39 UTC, JJ commented on README.md
> +Esta desorganización causa retrasos en la atención de los clientes, errores en la disponibilidad de piezas y tiempos de espera más largos de lo necesario. Como resultado, no solo se afecta la satisfa
Si enuncias un problema, lo haces para que se pueda desarrollar en un producto, y lo que hablas se tiene que implementar eventualmente en una aplicación. Lo que estás diciendo en la primera frase es que con el sistema a, el que fuera es peor que el sistema b,  que es el que tú vas a programar. Eventualmente, tendrás que programar un test que diga algo así como

```
test "Organización", {
    is_less( atencionDeLosClientes(sistemaAntiguo), atencionDeLosClientes(sistemaNuevo) )
}
```

Y ese test debe pasar. ¿Crees realmente que serías capaz de programar una función `atencionDeLosClientes` que actúe sobre una estructura de datos `sistema` y que dé una puntuación que se pueda calificar?

2024-10-01 09:02 UTC, lmchaves commented
He trabajado en enfocar mejor la descripción del problema, siguiendo la metodología de Design Thinking en su fase de empatía.
Por este motivo, me he centrado en un solo problema organizativo, el cual está causando retrasos en las reparaciones y afectando tanto la satisfacción del cliente como la productividad del taller.

Espero que la descripción actual al problema sea correcta. @JJ

2024-10-01 11:15 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?
> 
>     * [x]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
>       a requerir que el usuario los introduzca?

En casos dudosos como este, tendrías que justificar que tienes esos datos. Si no los tienes y los inventas, no vas a solucionar el problema.

2024-10-01 11:16 UTC, JJ requested changes
El problema parece bien descrito, con medidas objetivas (pero recuerda que tendrás que programar una "situación base" y demostrar que tu algoritmo tiene menons retraso), pero como no has contestado la pregunta de la checklist, no está claro que tengas esos datos. Por favor acláralo y también quién es en concreto el cliente. ¿Trabajador? ¿Propietario?

2024-10-01 11:16 UTC, JJ commented on README.md
> +Un taller de coches está experimentando dificultades organizativas que impactan negativamente en su eficiencia operativa y la satisfacción del cliente. El problema principal radica en la falta de un
¿Tienes conocimiento  personal del problema? ¿Puedes tener datos sobre todo lo que estás diciendo?

2024-10-01 11:16 UTC, JJ commented on configuracion.md
> +# Configuración del Entorno de Desarrollo
Cuando pase este objetivo, o lo borras o lo transfieres a un directorio adecuado. No es buena práctica poner más ficheros que los necesarios en la raíz.

2024-10-02 09:44 UTC, lmchaves commented on README.md
> +Un taller de coches está experimentando dificultades organizativas que impactan negativamente en su eficiencia operativa y la satisfacción del cliente. El problema principal radica en la falta de un
Si que tengo conocimiento personal del problema ya que mi abuelo es propietario de un taller, y acerca de esta pregunta:  ¿Puedes tener datos sobre todo lo que estás diciendo? A que datos en concreto se refiere? @JJ

2024-10-02 13:15 UTC, JJ commented on README.md
> +Un taller de coches está experimentando dificultades organizativas que impactan negativamente en su eficiencia operativa y la satisfacción del cliente. El problema principal radica en la falta de un
A los que vayas a usar en tu programa, claro. En todo caso, has contestado positivamente a la pregunta 

>  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?

Si no sabías a qué datos se refería, ¿por qué has contestado positivamente?

2024-10-03 10:13 UTC, lmchaves commented on README.md
> +Un taller de coches está experimentando dificultades organizativas que impactan negativamente en su eficiencia operativa y la satisfacción del cliente. El problema principal radica en la falta de un
No, los datos para resolver el probelma si los tengo, no sabía exactamente a que datos se refería. @JJ

2024-10-03 10:15 UTC, JJ commented on README.md
> +Un taller de coches está experimentando dificultades organizativas que impactan negativamente en su eficiencia operativa y la satisfacción del cliente. El problema principal radica en la falta de un
Indícalo en el relato del problema. "Mi abuelo ha guardado no sé qué datos en una hoja Excel desde 1945 sobre su taller" (o lo que sea)

2024-10-03 15:20 UTC, lmchaves commented on README.md
> +Un taller de coches está experimentando dificultades organizativas que impactan negativamente en su eficiencia operativa y la satisfacción del cliente. El problema principal radica en la falta de un
Ya he agregado la información en la descripción del problema. @JJ

2024-10-03 15:42 UTC, JJ requested changes
Estaba aprobándote esto pero creo que no va a ser posible porque al no estar el problema concretado te vas a encontrar con muchos problemas desde el objetivo 1 (historias de usuario) hasta el 2 y el 4 (tests).
1. No está claro realmente cuál es el problema expresado en términos que sean testeables. Ni la frustración es testeable, ni la organización o falta de ella.
2. No está claro qué es realmente la solución posible al problema. Si es saber cuanto van a tardar en recuperarse las piezas para dar la cita entonces, es básicamente almacenar y recuperar. Si involucra algo más complejo que necesite un algoritmo o lógica de negocio, tendrás que aclararlo.
Finalmente, no has incluido la configuración que se pide en el guión.

2024-10-03 17:01 UTC, lmchaves commented
Viendo que este probmlea no era el correcto, ahora he trabajado sobre un nuevo enfoque, que presenta una situación más clara y testeable. @JJ

2024-10-03 17:32 UTC, JJ requested changes
En desarrollo ágil se trata de ir mejorando de forma incremental, aplicando siempre metodologías probadas y buenas prácticas. Si desechas la idea de trabajar con el taller, de la que sí tienes conocimiento personal, sin seguir la metodología de *design thinking*, es decir, hablando con tu abuelo e identificando ciertas necesidades con las que se pudiera trabajar, vas a empezar otra vez desde cero, pero lo peor es que no estarás siguiendo la metodología que lo que pretende es no sólo buscar un producto de calidad, sino también hacerlo con un mínimo de trabajo.

2024-10-03 17:32 UTC, JJ commented on README.md
> +Un estudiante universitario que vive solo enfrenta dificultades organizativas que afectan negativamente su productividad académica y su bienestar personal. El problema principal radica en la falta de
Uf, dificultades organizativas otra vez... Que generan estrés... ¿De veras crees que esto es una mejora con respecto al anterior? Siguen siendo cosas no testeables.

2024-10-03 17:32 UTC, JJ commented on README.md
> +Este problema requiere una solución que permita al estudiante planificar y gestionar sus actividades diarias de forma eficiente. Para ello, se podrían utilizar datos sobre sus horarios de clase, fech
Por favor, lee de nuevo [el guión](https://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n)

> No incluir palabras como “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

2024-10-04 13:31 UTC, lmchaves commented
He seguido lo que me dijiste en el último comentario, sobre la metodología design thinking, preguntandole a mi abuelo para buscar las necesidades con las que pueda trabajar, siguiendo con el taller pero cambiando el problema, con el objetivo de que sea testable (sin centarrme en un probelma de  organización, ni frustación ni estrés). @JJ

2024-10-04 15:19 UTC, JJ requested changes
¿De qué forma requiere esto algo de lógica de negocio? ¿No se soluciona almacenando y buscando?

2024-10-04 15:19 UTC, JJ commented on README.md
> +El taller necesita un sistema que permita optimizar la búsqueda de piezas en sus distintas sedes, facilitando la reparación del vehículo lo más pronto posible, garantizando que el cliente no tenga qu
¿El problema es buscar piezas? El guión, una vez más, dice:

> No incluir palabras como “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

2024-10-04 16:24 UTC, lmchaves commented
Como lo habia expresado antes la solución si era con almacendado y buscar nada, mas pero con la nueva actualización implica lógica de negocio avanzada que abarca optimización de recursos, decisiones estratégicas sobre logística y tiempos de entrega, así como predicción de demanda futura.@JJ

2024-10-04 18:41 UTC, JJ commented
> Como lo habia expresado antes la solución si era con almacendado y buscar nada, mas pero con la nueva actualización implica lógica de negocio avanzada que abarca optimización de recursos, decisiones estratégicas sobre logística y tiempos de entrega, así como predicción de demanda futura.@JJ

"Así como" no es una palabra que entre en la descripción de *un solo* problema. Voy a ver de todas formas.

2024-10-04 18:44 UTC, JJ requested changes
Te faltaría mostrar que has subido la clave pública a tu cuenta de GitHub. Y si puede ser, que la has usado también y no has hecho todas las operaciones desde la web.

2024-10-04 18:44 UTC, JJ commented on README.md
> +El sistema también debería ser capaz de predecir las futuras necesidades de piezas en función de patrones de demanda, evitando que quedar sin stock cuando más lo necesita. Esto permitirá al taller re
*También* no entra en el vocabulario de la descripción de *un solo* problema. Puedes borrarlo de aquí (antes o después de mergear) e incluirlo como HU en el objetivo siguiente.

2024-10-04 18:44 UTC, JJ commented on configuracion.md
> +# Configuración del Entorno de Desarrollo
Por favor, resuelve todos los comentarios para que tenga claro que lo has leído y entendido.

2024-10-05 09:54 UTC, lmchaves commented
En pricipio ya está todo. @JJ

2024-10-07 05:27 UTC, JJ requested changes
En principio la parte del problema que has formulado de las líneas 4 al 7 del README parece un problema razonable. Resuelve los otros comentarios y por favor trata de entender por qué se hacen esos comentarios y lo que se espera que hagas.

2024-10-07 05:27 UTC, JJ commented on README.md
> +El sistema debería ser capaz de predecir las futuras necesidades de piezas en función de patrones de demanda, evitando que quedar sin stock cuando más lo necesita. Esto permitirá al taller reducir re
¿Has mirado el [fichero de errores comunes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#en-el-contenido) donde dice:

> Los deseos del cliente son órdenes, y eso significa que si el cliente quiere que vuestra aplicación haga algo, tendréis que testear que efectivamente lo hace. Si el problema es maximizar ventas, tendréis que examinar cuales son las ventas con el método actual (o aleatorio, lo que sea) y después con vuestro algoritmo, y ver que es superior estricto. Si queréis predecir, tendréis que programar vosotros un algoritmo que prediga y comprobar con datos que efectivamente lo hace.

Predecir implica que tienes un conjunto de datos suficiente de necesidades de piezas para poder entrenar el algoritmo, y que *tú* vas a escribir ese algoritmo y que lo prediga con la necesidad suficiente. ¿Tienes todo eso?

2024-10-07 05:27 UTC, JJ commented on README.md
> +https://github.com/lmchaves/OrganizarTaller/pull/1
¿Qué necesidad cubre esto?
También, ¿crees que quitar la palabra "también" de una descripción realmente elimina el hecho de que estás describiendo varios "problemas" (en realidad no, es una solución, no un problema) en vez de uno solo? Lo que has hecho aquí: 90c0077d322f46de62fc0044a453f4f340907485
Se trata de que resolváis realmente los comentarios, no simplemente que lo eliminéis. Hacer lo que has hecho simplemente genera más trabajo por las dos partes.

2024-10-07 07:45 UTC, lmchaves commented
He revisado sus comentarios y he ajustado mi propuesta en consecuencia. He eliminado la parte sobre la predicción de futuras necesidades de piezas (ya que implica una complejidad adicional que no puedo abordar en esta fase del proyecto). @JJ

2024-10-07 08:01 UTC, JJ requested changes
Por favor, trata de ajustarte no solo a las formalidades (eliminar comentarios), sino también al fondo del asunto. 
Ten también en cuenta que estás planteando un problema de optimización multiobjetivo, y que has dicho que *tienes los datos* para el mismo. No vale que cuando llegues al objetivo 4 te inventes los costos y tiempos que pones aquí, porque si lo haces no estarás resolviendo ningún problema, simplemente proporcionando datos a tu programa para que pase los tests. Si de acuerdo a esto quieres contextualizar un poco el problema o aclarar de donde vas a saar los datos, te lo agradezco también, aunque no es imprescindible para pasar este objetivo.

2024-10-07 08:01 UTC, JJ commented on README.md
> +https://github.com/lmchaves/OrganizarTaller/pull/1
Te rogaría que si modificas una línea para eliminar un comentario, elimines también la causa del mismo. Este enlace, ¿qué necesidad cubre?

2024-10-07 08:30 UTC, lmchaves commented
Entonces para aclarar de donde saco los datos lo pongo en la descripción del porblema? @JJ

2024-10-07 08:37 UTC, JJ commented
> Entonces para aclarar de donde saco los datos lo pongo en la descripción del porblema? @JJ

En realidad es para que tú mismo te des cuenta si puedes seguir adelante con esto, y a la vez contestar a dos de las preguntas de la lista de comprobación: la que dice si se tiene conocimiento personal del problema y si se tienen datos para poder hacer pruebas sobre el mismo.

2024-10-07 08:49 UTC, lmchaves commented
Si, si puedo seguir, tengo los datos sobre costos y tiempos de los transportes @JJ

2024-10-07 09:01 UTC, JJ commented
> Si, si puedo seguir, tengo los datos sobre costos y tiempos de los transportes @JJ

Dilo así en el documento, por favor.

2024-10-07 09:04 UTC, JJ requested changes
Por favor, elimina la línea indicada e incluye lo hablado.

2024-10-07 09:04 UTC, JJ commented on README.md
> +https://github.com/lmchaves/OrganizarTaller/pull/1
¿Y una vez más, crees que debes incluir esto?

2024-10-07 09:07 UTC, lmchaves commented on README.md
> +https://github.com/lmchaves/OrganizarTaller/pull/1
Es que a mi aqui no me sale nada, me salen lineas vacías (le adjunto foto) @JJ 
![Captura de pantalla 2024-10-07 110615](https://github.com/user-attachments/assets/2a373f2d-8708-4d76-82cd-5e87f380e0f4)

2024-10-07 15:28 UTC, JJ commented on README.md
> +https://github.com/lmchaves/OrganizarTaller/pull/1
¿No hay en la foto un enlace en la línea 12?

2024-10-07 16:14 UTC, lmchaves commented on README.md
> +https://github.com/lmchaves/OrganizarTaller/pull/1
Vale, lo siento

2024-10-07 16:48 UTC, lmchaves commented
Falataría algo mas? @JJ

2024-10-07 17:09 UTC, JJ approved these changes
:+1: 
Comienza lo antes posible con el siguiente objetivo, por favor, si no quieres que se retrasen todas las entregas.

2024-10-08 13:29 UTC, merged