[IV-24-25] Objetivo 3
lmchaves/OrganizarTaller pull request #23
Opened 2024-12-13 16:32 UTC by lmchaves

* [x] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [x] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [x] ¿Ese issue está asignado a un milestone?
* [x] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [x] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [x] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [x] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2024-12-13 18:29 UTC, Carlosmapego8 requested changes
Buenas, se me ha asignado revisión en tu PR. Te dejo un par de comentarios

2024-12-13 18:29 UTC, Carlosmapego8 commented on docs/gestor_dependencias.md
> +Elegiría PDM por su rapidez y simplicidad, aunque varias cumplen el estándar PEP 621. Aunque Poetry destaca en documentación, es más lento, y Hatch tiene menos recursos. Pipenv está desactualizado, y
Te dejo un extracto de los errores frecuentes
>No establecer de antemano cuales son los criterios de elección de las diferentes herramientas.

Realizas la elección, eso es cierto, pero no con unos criterios previamente establecidos

2024-12-13 18:29 UTC, Carlosmapego8 commented on docs/gestor_tareas.md
> +Invoke es ideal para proyectos centrados exclusivamente en Python, pero Make te permite gestionar tareas en cualquier lenguaje, lo que lo hace más adecuado a largo plazo.
Lo mismo que en el anterior

2024-12-14 14:40 UTC, lmchaves commented on docs/gestor_dependencias.md
> +Elegiría PDM por su rapidez y simplicidad, aunque varias cumplen el estándar PEP 621. Aunque Poetry destaca en documentación, es más lento, y Hatch tiene menos recursos. Pipenv está desactualizado, y
Aquí esta solucionado: [39ff4ea](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/39ff4ea21a375cc1c91f12f7b18aa47cf1e91e11)

2024-12-14 14:41 UTC, lmchaves commented on docs/gestor_tareas.md
> +Invoke es ideal para proyectos centrados exclusivamente en Python, pero Make te permite gestionar tareas en cualquier lenguaje, lo que lo hace más adecuado a largo plazo.
Aqui esta resuelto: [eb1e16f](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/eb1e16f6167fd85b2aed902976e2ff1b71277303)

2024-12-15 15:48 UTC, lmchaves commented
@Carlosmapego8 ya puedes revisar por si hay algo que todavía este mal

2024-12-16 11:35 UTC, Carlosmapego8 approved these changes
Por mi parte los veo bien @lmchaves, tienes mi aprobación

2024-12-16 15:53 UTC, hossam1522 reviewed
Buenas! Se me ha asignado revisar tu issue, te dejo algunos comentarios.

2024-12-16 15:53 UTC, hossam1522 commented on README.md
> +make check check
typo

2024-12-16 15:53 UTC, hossam1522 commented on docs/gestor_dependencias.md
> +2. **Rendimiento:** Gestores rápidos y ligeros que no ralenticen el flujo de trabajo.
¿Realmente crees que es un criterio relevante? Me refiero, dudo que notes diferencias de rendimiento entre unos y otros. Además, ¿cómo lo medirías?

2024-12-16 15:53 UTC, hossam1522 commented on docs/gestor_dependencias.md
> +3. **Documentación y comunidad:** Herramientas con una comunidad activa y buena documentación para facilitar la resolución de problemas.
¿Cómo se valora si una documentación es buena o no?

2024-12-16 15:53 UTC, hossam1522 commented on docs/gestor_dependencias.md
> +Elegiría PDM por su rapidez y simplicidad, aunque varias cumplen el estándar PEP 621. Aunque Poetry destaca en documentación, es más lento, y Hatch tiene menos recursos. Pipenv está desactualizado, y
Descartas, por ejemplo, Pipenv por estar desactualizado, pero no puedes descartar uno por algo que no esté entre los criterios.

2024-12-16 15:53 UTC, hossam1522 commented on docs/gestor_tareas.md
> +2. **Compatibilidad con el lenguaje del proyecto:** Preferencia por herramientas integradas nativamente con Python o independientes del lenguaje.
¿No es demasiado obvio quiźas?

2024-12-16 15:53 UTC, hossam1522 commented on docs/gestor_tareas.md
> +3. **Capacidades específicas:** Funcionalidades como ejecución remota, definición de tareas complejas o soporte para múltiples entornos.
¿Realmente necesitas alguna de las 3 cosas?

2024-12-16 15:53 UTC, hossam1522 commented on docs/gestor_tareas.md
> +5. **Escalabilidad y aplicabilidad a largo plazo:** Adecuación para proyectos de diferentes tamaños y lenguajes, con posibilidad de expansión futura.
No deberías pensar en nada relacionado con el largo plazo. Eso es deuda técnica, la cual se debe evitar.

2024-12-16 15:53 UTC, hossam1522 commented on docs/gestor_tareas.md
> +Paramiko es una librería Python que proporciona una implementación del protocolo SSH. Permite la ejecución remota de comandos en sistemas a través de SSH y la transferencia se gura de archivos. Su us
typo: se gura

2024-12-16 15:53 UTC, hossam1522 commented on docs/gestor_tareas.md
> +Invoke es ideal para proyectos centrados exclusivamente en Python, pero Make te permite gestionar tareas en cualquier lenguaje, lo que lo hace más adecuado a largo plazo.
Lo comentado antes. Deuda técnica

2024-12-17 10:24 UTC, wickeet reviewed
Los cambios que tienes que hacer son sencillos. ¡Ánimo que te falta poco!

2024-12-17 10:24 UTC, wickeet commented on docs/gestor_dependencias.md
> +4. **Simplicidad de uso:** Gestores fáciles de instalar, configurar y usar, incluso para desarrolladores menos experimentados.
¿La simplicidad es algo objetivo o algo más bien basado en experiencia o conocimiento de herramientas similares?

2024-12-17 10:24 UTC, wickeet commented on docs/gestor_tareas.md
> +6. **Complejidad añadida:** Se penalizan herramientas que introducen más complejidad de la necesaria para el proyecto.
¿Qué supone una complejidad añadida? No creo que sea mal criterio pero igual podrías ser un poco más específico.

2024-12-17 10:24 UTC, wickeet commented on Makefile
> +init_project:
¿Esta comprobación es realmente necesaria? A no ser que el usuario final borre el archivo, algo que sería ponerse trabas a si mismo, o que tu quitases el archivo del repositorio (no tiene ningún sentido), el archivo va a estar ahí

2024-12-17 10:41 UTC, lmchaves commented on docs/gestor_tareas.md
> +Invoke es ideal para proyectos centrados exclusivamente en Python, pero Make te permite gestionar tareas en cualquier lenguaje, lo que lo hace más adecuado a largo plazo.
Aqui esta solucionado: [19e98aa](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/19e98aacb299ca97fe1a8c8048a8919e60595b47)

2024-12-17 10:41 UTC, lmchaves commented on docs/gestor_tareas.md
> +Paramiko es una librería Python que proporciona una implementación del protocolo SSH. Permite la ejecución remota de comandos en sistemas a través de SSH y la transferencia se gura de archivos. Su us
ya esta arreglado [b72e7cc](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/b72e7ccb56c6a265e900fe6a3d65a34f54278758)

2024-12-17 10:41 UTC, lmchaves commented on docs/gestor_tareas.md
> +5. **Escalabilidad y aplicabilidad a largo plazo:** Adecuación para proyectos de diferentes tamaños y lenguajes, con posibilidad de expansión futura.
Aqui esta solucionado: [19e98aa](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/19e98aacb299ca97fe1a8c8048a8919e60595b47)

2024-12-17 10:42 UTC, lmchaves commented on docs/gestor_tareas.md
> +3. **Capacidades específicas:** Funcionalidades como ejecución remota, definición de tareas complejas o soporte para múltiples entornos.
Aqui esta solucionado: [19e98aa](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/19e98aacb299ca97fe1a8c8048a8919e60595b47)

2024-12-17 10:42 UTC, lmchaves commented on docs/gestor_tareas.md
> +2. **Compatibilidad con el lenguaje del proyecto:** Preferencia por herramientas integradas nativamente con Python o independientes del lenguaje.
Ya ha sido modificado [19e98aa](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/19e98aacb299ca97fe1a8c8048a8919e60595b47)

2024-12-17 10:42 UTC, lmchaves commented on docs/gestor_dependencias.md
> +Elegiría PDM por su rapidez y simplicidad, aunque varias cumplen el estándar PEP 621. Aunque Poetry destaca en documentación, es más lento, y Hatch tiene menos recursos. Pipenv está desactualizado, y
Ya lo he añadido: [5161cb5](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/5161cb554b5943fba117b039806183da36ab33cd)

2024-12-17 10:43 UTC, lmchaves commented on docs/gestor_dependencias.md
> +2. **Rendimiento:** Gestores rápidos y ligeros que no ralenticen el flujo de trabajo.
Ya ha sido modificado [19e98aa](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/19e98aacb299ca97fe1a8c8048a8919e60595b47)

2024-12-17 10:43 UTC, lmchaves commented on README.md
> +make check check
Ya esta solucionado: [2b342ea](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/2b342eab19ad5e8ed60dc575f57c84e1aa5050b3)

2024-12-17 10:46 UTC, lmchaves commented on docs/gestor_dependencias.md
> +3. **Documentación y comunidad:** Herramientas con una comunidad activa y buena documentación para facilitar la resolución de problemas.
Me refiero a valorar considerando su claridad, cantidad de ejemplos prácticos, y facilidad para encontrar soluciones a problemas comunes(también influye la cantidad de recursos adicionales disponibles, como tutoriales, foros y comunidades activas)

2024-12-17 10:55 UTC, lmchaves commented on Makefile
> +init_project:
Si, no es necesaria [ba4d472](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/ba4d472c0cf1c6b115d53f818b7afb01f4f20f70)

2024-12-17 10:57 UTC, lmchaves commented on docs/gestor_dependencias.md
> +4. **Simplicidad de uso:** Gestores fáciles de instalar, configurar y usar, incluso para desarrolladores menos experimentados.
Aqui ha sido eliminado al ser un criterio subjetivo: [f213777](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/f213777b0a71340ccd1fa1bf0f3fc342e31f3eaf)

2024-12-17 10:57 UTC, lmchaves commented on docs/gestor_tareas.md
> +6. **Complejidad añadida:** Se penalizan herramientas que introducen más complejidad de la necesaria para el proyecto.
Aqyui está expliacado mejor: [a2f9e40](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/a2f9e40c82cb6a1a63d76a14f8c8ba68eda6c57a)

2024-12-17 10:59 UTC, lmchaves commented
Gracias @hossam1522 y @wickeet ya he resuleto los comentarios

2024-12-18 11:03 UTC, lmchaves commented
@JJ ya esta listo para revisión

2024-12-19 07:52 UTC, JJ reviewed
Por favor, mira también los errores frecuentes.

2024-12-19 07:52 UTC, JJ commented on docs/gestor_dependencias.md
> +1. **Cumplimiento de estándares:** Preferencia por gestores que sigan el estándar PEP 621, garantizando mejores prácticas y compatibilidad futura.
PEP 621 es para los metadatos del proyecto; los que indican las dependencias son otros. En todo caso, enlázalos para que sea más fácil acceder a ellos.

2024-12-19 07:52 UTC, JJ commented on docs/gestor_dependencias.md
> +2. **Documentación y comunidad:** Herramientas con una comunidad activa y buena documentación para facilitar la resolución de problemas. Será medido:
Explícitamente os digo que no es un buen criterio, tanto en el guión como en los errores frecuentes.

2024-12-19 07:52 UTC, JJ commented on docs/gestor_dependencias.md
> +Combina **pip** y **env**, instala los paquetes mediante Pipfile.lock o Pipfile (no son estándares).
¿Qué estándar sigue?

2024-12-19 07:52 UTC, JJ commented on docs/gestor_dependencias.md
> +Soporta múltiples entornos virtuales como Hatch, pero también permite una integración más sencilla con otros entornos como Docker.
¿Tiene que ver algo con los criterios? Si no lo hace, por favor no incluyáis información irrelevante para la elección o para la corrección.

2024-12-19 07:52 UTC, JJ commented on docs/gestor_dependencias.md
> +(se puede ver como teinen mas de 1000 abiertos de hace minutos u horas, respondend bastante rápido).
typo: teinen

2024-12-19 07:52 UTC, JJ commented on docs/gestor_tareas.md
> +Paramiko es una librería Python que proporciona una implementación del protocolo SSH. Permite la ejecución remota de comandos en sistemas a través de SSH y la transferencia segura de archivos. Su uso
¿Y esto qué tiene que ver con gestionar tareas?

2024-12-19 07:52 UTC, JJ commented on docs/gestor_tareas.md
> +Fabric (basada en Paramiko) es una herramienta basada en Python para ejecutar comandos de shell de manera remota a través de SSH. Permite automatizar tareas en servidores y despliegues, extendiendo l
¿Es eso lo que buscamos? ¿De manera *remota*?

2024-12-19 07:52 UTC, JJ commented on docs/gestor_tareas.md
> +Rake está orientado principalmente a proyectos escritos en Ruby, lo que limita su utilidad para proyectos en Python y otros lenguajes. Aunque tiene una buena integración con Ruby, su comunidad y docu
Por favor, mira los errores frecuentes.

2024-12-19 07:52 UTC, JJ commented on Makefile
> +		$(PDM_PATH) run flake8 src/
¿Esto *solo* comprueba la sintaxis?

2024-12-19 08:28 UTC, lmchaves commented on Makefile
> +		$(PDM_PATH) run flake8 src/
Aquí esta corregido: [98da6e5](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/98da6e50a37b9d594e004cb319af351bc98de9bb)

2024-12-19 08:28 UTC, lmchaves commented on docs/gestor_tareas.md
> +Rake está orientado principalmente a proyectos escritos en Ruby, lo que limita su utilidad para proyectos en Python y otros lenguajes. Aunque tiene una buena integración con Ruby, su comunidad y docu
Aqui esta solucionado: [0e4affe](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/0e4affe8f1ea53e50ac80d823bc7d2de95b014a6)

2024-12-19 08:28 UTC, lmchaves commented on docs/gestor_tareas.md
> +Fabric (basada en Paramiko) es una herramienta basada en Python para ejecutar comandos de shell de manera remota a través de SSH. Permite automatizar tareas en servidores y despliegues, extendiendo l
Aqui esta solucionado: [0e4affe](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/0e4affe8f1ea53e50ac80d823bc7d2de95b014a6)

2024-12-19 08:29 UTC, lmchaves commented on docs/gestor_tareas.md
> +Paramiko es una librería Python que proporciona una implementación del protocolo SSH. Permite la ejecución remota de comandos en sistemas a través de SSH y la transferencia segura de archivos. Su uso
Aqui esta solucionado: [0e4affe](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/0e4affe8f1ea53e50ac80d823bc7d2de95b014a6)

2024-12-19 08:29 UTC, lmchaves commented on docs/gestor_dependencias.md
> +(se puede ver como teinen mas de 1000 abiertos de hace minutos u horas, respondend bastante rápido).
Aqui esta solucionado: [0e4affe](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/0e4affe8f1ea53e50ac80d823bc7d2de95b014a6)

2024-12-19 08:29 UTC, lmchaves commented on docs/gestor_dependencias.md
> +Soporta múltiples entornos virtuales como Hatch, pero también permite una integración más sencilla con otros entornos como Docker.
[d373061](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/d37306170076c82fbdf7f86e08f034d6dd56a378)

2024-12-19 08:30 UTC, lmchaves commented on docs/gestor_dependencias.md
> +Combina **pip** y **env**, instala los paquetes mediante Pipfile.lock o Pipfile (no son estándares).
Aqui esta solucionado: [d373061](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/d37306170076c82fbdf7f86e08f034d6dd56a378)

2024-12-19 08:30 UTC, lmchaves commented on docs/gestor_dependencias.md
> +2. **Documentación y comunidad:** Herramientas con una comunidad activa y buena documentación para facilitar la resolución de problemas. Será medido:
Aqui esta solucionado: [d373061](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/d37306170076c82fbdf7f86e08f034d6dd56a378)

2024-12-19 08:30 UTC, lmchaves commented on docs/gestor_dependencias.md
> +1. **Cumplimiento de estándares:** Preferencia por gestores que sigan el estándar PEP 621, garantizando mejores prácticas y compatibilidad futura.
Aqui esta solucionado: [d373061](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/d37306170076c82fbdf7f86e08f034d6dd56a378)

2024-12-19 08:31 UTC, lmchaves commented
@JJ ya está listo para revisión

2024-12-19 08:43 UTC, JJ requested changes
Simplemente tratad de buscar  una herramienta u opción que compruebe la sintaxis.

2024-12-19 08:43 UTC, JJ commented on Makefile
> +# Ejecutar pylint para revisar la sintaxis y estilo del código
Por favor, usad herramientas u opciones de comando que *solo* comprueben la sintaxis. Esto es un linter, diferente a flake8, que te aplica PEP8, pero también un linter (como su nombre indica)

2024-12-19 08:59 UTC, lmchaves commented on Makefile
> +# Ejecutar pylint para revisar la sintaxis y estilo del código
Ya lo he cambiado aqui: [48a789e](https://github.com/lmchaves/OrganizarTaller/pull/23/commits/48a789e4c87a0a898f47d55c406cd32845de06de)

2024-12-19 09:19 UTC, lmchaves commented
Revisión @JJ

2024-12-19 09:23 UTC, JJ approved these changes
👍

2024-12-19 14:57 UTC, merged