[IV-24-25] Objetivo 4
lmchaves/OrganizarTaller pull request #25
Opened 2024-12-23 14:26 UTC by lmchaves

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2024-12-23 18:05 UTC, hossam1522 reviewed
Buenas! Se me ha asignado revisar tu issue. Te dejo algunos comentarios. ¡Ánimo!

2024-12-23 18:05 UTC, hossam1522 commented on README.md
> +make check check
¿Y esto? ¿No debería ser simplemente `make check`?

2024-12-23 18:05 UTC, hossam1522 commented on docs/test_runner.md
> +2. **Pruebas automáticas:** ejecutar pruebas de forma automatizada.
Demasiado obvio como para ser un criterio, al final eso es lo que se busca en la búsqueda de una herramienta de este estilo

2024-12-23 18:05 UTC, hossam1522 commented on docs/test_runner.md
> +3. **Biblioteca de aserciones**: biblioteca adecuada para verificar las condiciones esperadas en los tests.
Igual deberías expresarlo mejor. ¿Te refieres a que tenga aserciones la biblioteca? No se entiende demasiado bien realmente.

2024-12-23 18:05 UTC, hossam1522 commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada debido a su facilidad de uso, mantenimiento activo, amplia comunidad y biblioteca de aserciones nativa, que simplifica la escritura
Has descartado Unittest porque su curva de aprendizaje es más pronunciada (aunque esto se podría llegar a considerar subjetivo). No deberías descartar una herramienta por algo que no está entre los criterios.

2024-12-23 18:05 UTC, hossam1522 commented on src/pedido.py
> +    # Calcular la distancia entre las sedes
Si el código no se entiende sin comentarios y te parece necesario añadirlos, estás incurriendo en deuda técnica. Aquí y en todo el resto de comentarios que tengas en el código.

2024-12-23 19:39 UTC, MarioRgzLpz commented on docs/test_runner.md
Tienes que echarle un vistazo a este fichero. No has hablado nada ni de aserciones ni de herramientas CLI. Además hay algunas typos.

2024-12-23 19:40 UTC, MarioRgzLpz commented
Buenas, se me ha asignado revisar tu PR. A parte de lo ya mencionado por @hossam1522 te dejo algunos comentarios.

2024-12-23 19:42 UTC, MarioRgzLpz commented on docs/test_runner.md
Aquí solo has tratado uno de los distintos niveles de abstracción que encontramos para las herramientas de testing. Debes añadir algo relacionado con las aserciones y las herramientas CLI. Además tienes algunas typos, intenta corregirlas.

2024-12-23 19:43 UTC, MarioRgzLpz commented on docs/test_runner.md
> +Permite ejecutar tests de foram automatizada mediante el comando **pytest**, es activamente mantenido y cuenta con una comunidad extensa, lo que asegura la resolución rápida de problemas (permitiendo
```suggestion
Permite ejecutar tests de forma automatizada mediante el comando **pytest**, es activamente mantenido y cuenta con una comunidad extensa, lo que asegura la resolución rápida de problemas (permitiendo tener muchos recursos).
```
Typo

2024-12-24 10:10 UTC, lmchaves commented on docs/test_runner.md
> +2. **Pruebas automáticas:** ejecutar pruebas de forma automatizada.
ya esta corregido [4734153](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/473415373fc644f6edb3e57d54f71f2b3fc341c3)

2024-12-24 10:10 UTC, lmchaves commented on docs/test_runner.md
> +3. **Biblioteca de aserciones**: biblioteca adecuada para verificar las condiciones esperadas en los tests.
aqui esta mejor explicado: [4734153](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/473415373fc644f6edb3e57d54f71f2b3fc341c3)

2024-12-24 10:11 UTC, lmchaves commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada debido a su facilidad de uso, mantenimiento activo, amplia comunidad y biblioteca de aserciones nativa, que simplifica la escritura
ya lo he cambiado: [4734153](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/473415373fc644f6edb3e57d54f71f2b3fc341c3)

2024-12-24 10:23 UTC, lmchaves commented on README.md
> +make check check
Es que al hacr la entrega me daba error al poenr solo make check, aqui lo corrijo: [4734153](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/473415373fc644f6edb3e57d54f71f2b3fc341c3)

2024-12-24 10:24 UTC, lmchaves commented on docs/test_runner.md
Aqui he añadirodo sobre las bibliotecas de aserciones usadsas en cda test runner y su uso en CLI: [b11186e](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/b11186ef34a3dee8ba1bb24dcfdb63b688664054)

2024-12-24 10:24 UTC, lmchaves commented on docs/test_runner.md
> +Permite ejecutar tests de foram automatizada mediante el comando **pytest**, es activamente mantenido y cuenta con una comunidad extensa, lo que asegura la resolución rápida de problemas (permitiendo
ya eta corergido: [b11186e](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/b11186ef34a3dee8ba1bb24dcfdb63b688664054)

2024-12-24 10:27 UTC, hossam1522 commented on README.md
> +make check check
Claro, es que en el iv.yaml solo deberías poner make y no make check, por eso te peta

2024-12-24 10:30 UTC, lmchaves commented on src/pedido.py
> +    # Calcular la distancia entre las sedes
Ya lo he cmabiado para que el codigo se entienda sin los comnetarios : [2a133ca](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/2a133ca5d34fbb2446587ee00aaf36b32e29cbaf)

2024-12-24 10:30 UTC, lmchaves commented
Gracias @MarioRgzLpz y @hossam1522 por los comentarios, ya los he resuleto, si véis algo más comentadlo

2024-12-25 18:50 UTC, lmchaves commented
@JJ ya esta listo para revisión

2024-12-26 04:52 UTC, MarioRgzLpz approved these changes

2024-12-30 11:52 UTC, juanmaaf requested changes
Buenas, se me ha asignado revisar tu PR. En general está bastante bien, pero he realizado una serie de puntualizaciones en la elección de las herramientas.

2024-12-30 11:52 UTC, juanmaaf commented on docs/test_runner.md
> +1. **Herramientas activas:** Preferencia por herramientas activamente mantenidas y actualizadas para evitar problemas de tecnologías obsoletas.
Podrías considerar incluir la fuente de la que obtienes la información para validar este criterio.

2024-12-30 11:52 UTC, juanmaaf commented on docs/test_runner.md
> +# Herramienta para tests
Ingual que ha comentado @MarioRgzLpz , deberías tratar los distintos niveles de abstracción. Buscando bibliotecas de aserciones, test runners y herramientas CLI, ¿solo has encontrado esas herramientas? Considera evaluar cada nivel de abstracción por separado y encontrarás más herramientas.

2024-12-30 11:52 UTC, juanmaaf commented on docs/test_runner.md
> +2. **Biblioteca de aserciones**: la herramienta debe incluir una biblioteca adecuada para verificar condiciones esperadas en los tests de manera clara y legible.
¿Qué es una biblioteca adecuada? Viendo la comparación que has hecho de las herramientas en cuanto a este criterio, hablas de que la herramienta ofrezca métodos que simplifiquen la aserción. Considera especificarlo en el criterio, ya que actualmente parece subjetivo.

2024-12-30 15:16 UTC, lmchaves commented on docs/test_runner.md
> +2. **Biblioteca de aserciones**: la herramienta debe incluir una biblioteca adecuada para verificar condiciones esperadas en los tests de manera clara y legible.
Lo especifico aqui: [a5b4861](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/a5b4861d8a0328f2ec60527c0da4bf36a03f7524)

2024-12-30 15:16 UTC, lmchaves commented on docs/test_runner.md
> +# Herramienta para tests
Aqui he tratado mas a donof los distintos nievels, encontrando mas herramietas [a5b4861](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/a5b4861d8a0328f2ec60527c0da4bf36a03f7524)

2024-12-30 15:16 UTC, lmchaves commented on docs/test_runner.md
> +1. **Herramientas activas:** Preferencia por herramientas activamente mantenidas y actualizadas para evitar problemas de tecnologías obsoletas.
He añadido las fuentes [a5b4861](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/a5b4861d8a0328f2ec60527c0da4bf36a03f7524)

2024-12-30 15:17 UTC, lmchaves commented
Gracias @juanmaaf por los comentarios, ya los he resuelto

2025-01-01 16:04 UTC, lmchaves commented
@JJ ya está lsito apra revisión

2025-01-02 07:57 UTC, JJ requested changes
Por favor, lee los [errores comunes](https://github.com/JJ/IV-/blob/master/errores/objetivo-4.md#sobre-las-diferentes-herramientas):

> Hablar de "herramientas de test" sin especificar qué es lo que hacen esas herramientas de test. No existen las herramientas de test, existen herramientas que llevan a cabo diferentes funcionalidades relacionadas con los tests. El tipo de esas herramientas, para las funcionalidades que se requieren en el objetivo, es lo que hay que hay que reflejar aquí.

2025-01-02 07:57 UTC, JJ commented on docs/test_runner.md
> +1. **Herramientas activas:** Preferencia por herramientas activamente mantenidas y actualizadas para evitar problemas de tecnologías obsoletas.
Podías añadirla *aquí*

2025-01-02 07:57 UTC, JJ commented on docs/test_runner.md
> +Para seleccionar la herramienta para tests, se han considerado los siguientes criterios:
No existen las "herramientas para tests".

2025-01-02 09:44 UTC, lmchaves commented on docs/test_runner.md
> +Para seleccionar la herramienta para tests, se han considerado los siguientes criterios:
Aqui esta modificado y con las fuentes en el criterio: [0ed63f1](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/0ed63f1b1633847d5be68e3d0ad6d5187314096b)

2025-01-02 09:44 UTC, lmchaves commented
Ya esta listo @JJ

2025-01-02 15:15 UTC, juanmaaf requested changes
Dale una vuelta de nuevo a la elección de herramientas. Considera elegir varias herramientas si lo ves conveniente. No es necesario que la herramienta abarque los tres niveles de abstracción (test runner, biblioteca de aserciones y herramienta CLI para ejecutar los test).

2025-01-02 15:15 UTC, juanmaaf commented on docs/test_runner.md
> +3. **Facilidad de ejecución desde CLI:** Capacidad para ejecutar pruebas fácilmente desde la línea de comandos, permitiendo ejecutar todos los tests o casos específicos.
Facilidad no es medible ni objetivo.

2025-01-02 15:15 UTC, juanmaaf commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada. Aunque Unittest es una herramienta estándar y ampliamente usada, Pytest es preferido debido a su mantenimiento activo, amplia comun
En los criterios no hablas de comunidad, por lo que no deberías diferenciar herramientas por ello. La elección debe basarse en los criterios establecidos.

2025-01-02 17:16 UTC, lmchaves commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada. Aunque Unittest es una herramienta estándar y ampliamente usada, Pytest es preferido debido a su mantenimiento activo, amplia comun
Ya he modificado y en las conclusiones ya se usan los criterios [4d265d5](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/4d265d5c7094bbccb71cf21d1a5ae46964d17e3b)

2025-01-02 17:16 UTC, lmchaves commented on docs/test_runner.md
> +3. **Facilidad de ejecución desde CLI:** Capacidad para ejecutar pruebas fácilmente desde la línea de comandos, permitiendo ejecutar todos los tests o casos específicos.
Se ha eliminado el criterio al no ser objetivo [4d265d5](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/4d265d5c7094bbccb71cf21d1a5ae46964d17e3b)

2025-01-02 17:17 UTC, lmchaves commented
@juanmaaf ya lo he resuelto

2025-01-03 07:39 UTC, lmchaves commented
@jj ya esta listo para revision

2025-01-03 11:18 UTC, JJ commented
> @JJ ya esta listo para revision

Espero a que lo revise @juanmaaf

2025-01-05 11:33 UTC, juanmaaf requested changes
Buenas tardes. Disculpa la demora en la revisión. Te he dejado una serie de puntualizaciones, pues observo errores frecuentes en la elección de las herramientas. Considera separar los criterios de elección de herramientas para cada nivel de abstracción.

2025-01-05 11:33 UTC, juanmaaf commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada debido a su mantenimiento activo, facilidad de uso y una biblioteca de aserciones integrada que simplifica la escritura y comprensió
Hablar de curva de aprendizaje no es medible ni objetivo. Además, estás comparando herramientas en base a criterios no especificados en el apartado "Criterios de Evaluación" al principio del archivo.

2025-01-05 11:33 UTC, juanmaaf commented on docs/test_runner.md
> +Pytest destaca por su simplicidad, mensajes automáticos detallados y mantenimiento activo. Ensure tiene una sintaxis explícita, mientras que Unittest permanece sólido para pruebas formales. PyHamcres
Evita incluir términos no medibles ni objetivos como "simplicidad". ¿Qué herramienta es más simple y por qué?

2025-01-05 11:33 UTC, juanmaaf commented on docs/test_runner.md
> +
¿Qué comando eliges para ejecutar los tests?

2025-01-05 11:33 UTC, juanmaaf commented on docs/test_runner.md
> +2. **Biblioteca de aserciones**: La herramienta debe incluir una biblioteca que permita verificar condiciones esperadas de los tests mediante métodos simples y legibles, proporcionando mensajes detal
¿Consideras que este criterio se debe tener en cuenta para elegir el test runner y el comando para ejecutar los tests?

2025-01-05 11:33 UTC, juanmaaf commented on docs/test_runner.md
> +3.
Elimina esta línea si no hay un tercer criterio.

2025-01-05 14:23 UTC, lmchaves commented on docs/test_runner.md
> +3.
ya esta corregido [37f7be9](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/37f7be9c00331acc8e1e241d1d2e022d50d1c723)

2025-01-05 14:23 UTC, lmchaves commented on docs/test_runner.md
> +2. **Biblioteca de aserciones**: La herramienta debe incluir una biblioteca que permita verificar condiciones esperadas de los tests mediante métodos simples y legibles, proporcionando mensajes detal
ya he cmabiado los criterios para los fierentes niveles de abstracción [37f7be9](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/37f7be9c00331acc8e1e241d1d2e022d50d1c723)

2025-01-05 14:23 UTC, lmchaves commented on docs/test_runner.md
> +
ya lo he incluido [37f7be9](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/37f7be9c00331acc8e1e241d1d2e022d50d1c723)

2025-01-05 14:24 UTC, lmchaves commented on docs/test_runner.md
> +Pytest destaca por su simplicidad, mensajes automáticos detallados y mantenimiento activo. Ensure tiene una sintaxis explícita, mientras que Unittest permanece sólido para pruebas formales. PyHamcres
he eliminado los términos no ibjetivos ni medibles [37f7be9](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/37f7be9c00331acc8e1e241d1d2e022d50d1c723)

2025-01-05 14:24 UTC, lmchaves commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada debido a su mantenimiento activo, facilidad de uso y una biblioteca de aserciones integrada que simplifica la escritura y comprensió
ya esta cambiado [37f7be9](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/37f7be9c00331acc8e1e241d1d2e022d50d1c723)

2025-01-05 14:24 UTC, lmchaves commented
ya esta corregido @juanmaaf

2025-01-07 09:45 UTC, juanmaaf requested changes
Has vuelto a cometer errores frecuentes. Revisa el archivo de errores frecuentes y te invito a revisar mi PR para que no cometas los errores que estoy cometiendo y estés más cerca de superar el objetivo.

2025-01-07 09:45 UTC, juanmaaf commented on docs/test_runner.md
> +2. **Variedad de aserciones:** Se valoran bibliotecas que ofrecen una amplia gama de métodos de verificación, permitiendo cubrir diferentes casos de tests y simplificando la validación de condiciones
Esto es un error frecuente. Te invito a revisar mi PR y verás que he cometido el mismo error. No es medible.

2025-01-07 09:45 UTC, juanmaaf commented on docs/test_runner.md
> +3. **Claridad de mensajes de error:** Es importante que proporcionen mensajes detallados y claros en caso de fallos, facilitando la identificación y solución de problemas durante el desarrollo de los
Volvemos a lo mismo. "Claridad" no es medible ni obbjetivo.

2025-01-07 09:45 UTC, juanmaaf commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada debido a su mantenimiento activo, facilidad de uso y una biblioteca de aserciones integrada que simplifica la escritura y comprensió
La facilidad de uso no es un criterio. Además es algo completamente subjetivo. En la conclusión, donde eliges la herramienta, debes tener en cuenta únicamente los criterios que hayas establecido inicialmente. Deben ser criterios objetivos.

2025-01-07 10:37 UTC, lmchaves commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada debido a su mantenimiento activo, facilidad de uso y una biblioteca de aserciones integrada que simplifica la escritura y comprensió
ya he modificado la conlusión: [3540126](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/3540126ccd2192c05f565b688d8f010cf989552b)

2025-01-07 10:38 UTC, lmchaves commented on docs/test_runner.md
> +3. **Claridad de mensajes de error:** Es importante que proporcionen mensajes detallados y claros en caso de fallos, facilitando la identificación y solución de problemas durante el desarrollo de los
he modificado la parte de claridad , pero como la definicion del criterio si me parece correcto ya que habo de mensajes detallados que si son medibles y objetivos (claridad no, lo he modificado) [3540126](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/3540126ccd2192c05f565b688d8f010cf989552b)

2025-01-07 11:24 UTC, lmchaves commented
ya esta corregido @juanmaaf

2025-01-07 14:46 UTC, lmchaves commented on docs/test_runner.md
> +2. **Variedad de aserciones:** Se valoran bibliotecas que ofrecen una amplia gama de métodos de verificación, permitiendo cubrir diferentes casos de tests y simplificando la validación de condiciones
aqui esta corregido: [290c627](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/290c6275261a042c320285bb5f366d6aff6a0c08)

2025-01-07 14:47 UTC, lmchaves commented
@juanmaaf ya está lsito para revisión

2025-01-08 16:34 UTC, juanmaaf approved these changes
Creo que no tengo más que añadir. Por mi parte tienes el aprobado.

2025-01-08 17:21 UTC, lmchaves commented
@jj ya está lsito para revisión

2025-01-08 18:00 UTC, JJ requested changes
Agradezco a @juanmaaf el esfuerzo realizado, desgraciadamente, no supera el objetivo.

2025-01-08 18:00 UTC, JJ commented on README.md
>  make check test
¿Seguro que esto es así?

2025-01-08 18:00 UTC, JJ commented on docs/test_runner.md
> +2. Se valoran bibliotecas que ofrecen diversos métodos de verificación (por ejemplo, assertEqual, assertTrue, assertRaises, etc.), permitiendo cubrir diferentes casos de tests y simplificando la vali
¿hay alguna que no los ofrezca? Por favor, lee [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-3.md):

> Entre esos criterios arbitrarios, a veces hay criterios que se cumplen en cualquier caso y que no sirven para diferenciar uno de otros.

2025-01-08 18:00 UTC, JJ commented on docs/test_runner.md
> +3. **Mensajes detallados de error:** Es importante que proporcionen mensajes detallados y claros en caso de fallos, facilitando la identificación y solución de problemas durante el desarrollo de los
¿Qué mensajes de error y quién puede medir lo detallados que son?
Por otro lado, este "criterio" ya me lo he encontrado varias veces, por lo que entra en juego la primera regla del apartado "sobre los criterios"

2025-01-08 19:40 UTC, lmchaves commented on README.md
>  make check test
Ya esta arreglado [1ee943d](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/1ee943d87f5e6bb00718cd3ad3c8fc8456e90949)

2025-01-08 19:40 UTC, lmchaves commented on docs/test_runner.md
> +2. Se valoran bibliotecas que ofrecen diversos métodos de verificación (por ejemplo, assertEqual, assertTrue, assertRaises, etc.), permitiendo cubrir diferentes casos de tests y simplificando la vali
ya he quitado este criterio, [2e6a5f4](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/2e6a5f461849caf8c275dc22e8e65b3aa84d3298)

2025-01-08 19:40 UTC, lmchaves commented on docs/test_runner.md
> +3. **Mensajes detallados de error:** Es importante que proporcionen mensajes detallados y claros en caso de fallos, facilitando la identificación y solución de problemas durante el desarrollo de los
ya ha lo he arreglado [2e6a5f4](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/2e6a5f461849caf8c275dc22e8e65b3aa84d3298)

2025-01-08 19:41 UTC, lmchaves commented
Ya he realiado als modifcaciones @JJ

2025-01-10 06:48 UTC, JJ requested changes
No he revisado los tests, pero por favor revísalos también mirando los errores frecuentes.

2025-01-10 06:48 UTC, JJ commented on README.md
> +make check
Añadiéndole un espacio fuerzas un cambio, y por tanto la evaluación. Por favor, evitad esto.

2025-01-10 06:48 UTC, JJ commented on docs/test_runner.md
> +2. **Complejidad añadida:** Se penalizan herramientas que introduzcan complejidad innecesaria para el proyecto, ya sea por depender de bibliotecas adicionales o por requerir una sintaxis excesivament
¿Con esto quieres decir que si viene incluida es mejor? Si es así, ¿porqué no pones eso en vez de poner un criterio que ni es medible ni, de hecho, comprensible?

2025-01-10 06:48 UTC, JJ commented on docs/test_runner.md
> +Testify es un test runner robusto, diseñado como una alternativa a Unittest. Proporciona una estructura clara para organizar tests y ofrece funcionalidades avanzadas como hooks para configurar y limp
¿Has visto lo que pone en la primera línea del README? ¿Qué tiene que ver con tu primer criterio?

2025-01-10 06:48 UTC, JJ commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada debido a su mantenimiento activo, y una biblioteca de aserciones integrada que simplifica la escritura y comprensión de los tests. U
¿Qué biblioteca de aserciones *integrada* tiene?
¿Qué pasa con la "complejidad"?

2025-01-10 06:48 UTC, JJ commented on docs/test_runner.md
> +Pytest utiliza una biblioteca de aserciones nativa que permite escribir afirmaciones simples como `assert actual == expected`. Esta biblioteca genera automáticamente mensajes detallados en caso de fa
No sólo no es `assert` parte de pytest, es que dijimos en clase que'es lo que era `assert`

2025-01-10 06:48 UTC, JJ commented on docs/test_runner.md
> +Nose2 no tiene su propia biblioteca de aserciones, pero es compatible con las bibliotecas estándar de Python como las de Unittest. Esto permite escribir pruebas utilizando métodos como `self.assertEq
O sea que estás incluyendo en las bibliotecas de aserciones una herramienta que no tiene su propia biblioteca de aserciones.

2025-01-10 06:48 UTC, JJ commented on docs/test_runner.md
> +Pytest destaca por sus mensajes automáticos detallados y mantenimiento activo. Ensure tiene una sintaxis explícita, mientras que Unittest permanece sólido para pruebas formales y puede combinarse con
¿Qué se ha elegido?

2025-01-10 06:48 UTC, JJ commented on docs/test_runner.md
> +- Se utiliza el comando `python -m unittest` para ejecutar todos los tests, o `python -m unittest ruta.TestClase.test_nombre` para casos concretos.
Luego no es una herramienta CLI.

2025-01-10 06:48 UTC, JJ commented on src/pedido.py
> +        tiempo_estimado_llegada=distancia / 80,
No se deben usar números mágicos. Ni aquí ni arriba.

2025-01-10 06:48 UTC, JJ commented on src/pedido.py
> +    distancia = sede_origen.calcular_distancia(sede_destino)
Por el principio de responsabilidad única, realizar un pedido *solo* debe realizar un pedido, no calcular distancias.

2025-01-10 06:48 UTC, JJ commented on src/pedido.py
> +                costo_transporte = distancia * 0.5
No solo estás haciendo esto con números mágicos, sino que estás repitiendo código aquí y arriba.

2025-01-10 06:48 UTC, JJ commented on src/pedido.py
> +            sede_optima = min(opciones, key=lambda x: x[1])
¿Te parece que usar el primer elemento de un vector para almacenar el costo sea una forma expresiva de modelizar un problema? ¿No tendrá Python una forma mejor de hacerlo?

2025-01-10 06:48 UTC, JJ commented on src/pedido.py
> +            if pieza in sede.inventario and sede.inventario[pieza][0] >= cantidad_requerida:
Esto es un if dentro de un for que está dentro de un for. Para empezar, es complejo de testear por la complejidad ciclomática. Para seguir, hay herramientas mejores en Python para hacer este mismo código de forma más expresiva. Para continuar, no se comprende qué condición es lo que estás poniendo como primer elemento de un array. Si no se comprende, es imposible de depurar y de testear. Por favor, trata de escribir *tú mismo* un código que sea más comprensible, o revisar críticamente lo que te emita una herramienta generativa para escribir *código limpio* más fácil de entender por el revisor (y por ti)  y de testear.

2025-01-10 10:41 UTC, lmchaves commented on docs/test_runner.md
> +2. **Complejidad añadida:** Se penalizan herramientas que introduzcan complejidad innecesaria para el proyecto, ya sea por depender de bibliotecas adicionales o por requerir una sintaxis excesivament
Aqui he cambiado el cirerio para que quede meor explicado [b4dd226](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/b4dd2265dfdb09ede50258ea371f7defd9089957)

2025-01-10 10:42 UTC, lmchaves commented on docs/test_runner.md
> +Testify es un test runner robusto, diseñado como una alternativa a Unittest. Proporciona una estructura clara para organizar tests y ofrece funcionalidades avanzadas como hooks para configurar y limp
Ya lo he quitado al estar en desuso: [e80e6a3](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/e80e6a36eb3e94349bfd101038b753e74863edff)

2025-01-10 10:42 UTC, lmchaves commented on docs/test_runner.md
> +Según los criterios establecidos, Pytest es la opción más adecuada debido a su mantenimiento activo, y una biblioteca de aserciones integrada que simplifica la escritura y comprensión de los tests. U
Ya he modificado [56e23b3](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/56e23b357f0f9e5682747537650cb7c2e6f39315)

2025-01-10 10:42 UTC, lmchaves commented on docs/test_runner.md
> +Pytest utiliza una biblioteca de aserciones nativa que permite escribir afirmaciones simples como `assert actual == expected`. Esta biblioteca genera automáticamente mensajes detallados en caso de fa
Ya ha sido arreglado [56e23b3](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/56e23b357f0f9e5682747537650cb7c2e6f39315)

2025-01-10 10:43 UTC, lmchaves commented on docs/test_runner.md
> +Nose2 no tiene su propia biblioteca de aserciones, pero es compatible con las bibliotecas estándar de Python como las de Unittest. Esto permite escribir pruebas utilizando métodos como `self.assertEq
Ya ha sido eliminado [56e23b3](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/56e23b357f0f9e5682747537650cb7c2e6f39315)

2025-01-10 10:43 UTC, lmchaves commented on docs/test_runner.md
> +Pytest destaca por sus mensajes automáticos detallados y mantenimiento activo. Ensure tiene una sintaxis explícita, mientras que Unittest permanece sólido para pruebas formales y puede combinarse con
Lo he cambiado para que quede claro qeu se escoge [56e23b3](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/56e23b357f0f9e5682747537650cb7c2e6f39315)

2025-01-10 10:43 UTC, lmchaves commented on docs/test_runner.md
> +- Se utiliza el comando `python -m unittest` para ejecutar todos los tests, o `python -m unittest ruta.TestClase.test_nombre` para casos concretos.
Ya lo he modificado [56e23b3](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/56e23b357f0f9e5682747537650cb7c2e6f39315)

2025-01-10 17:53 UTC, lmchaves commented on src/pedido.py
> +        tiempo_estimado_llegada=distancia / 80,
ya lo he resuelto: [6601616](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/66016166b8cd4c3ae31f3de193a2fc6bfe4ec709)

2025-01-10 17:53 UTC, lmchaves commented on src/pedido.py
> +    distancia = sede_origen.calcular_distancia(sede_destino)
ahora realizar_pedido solo realiza dicho pedido [6601616](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/66016166b8cd4c3ae31f3de193a2fc6bfe4ec709)

2025-01-10 17:53 UTC, lmchaves commented on src/pedido.py
> +                costo_transporte = distancia * 0.5
ya esta arreglado [6601616](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/66016166b8cd4c3ae31f3de193a2fc6bfe4ec709)

2025-01-10 17:54 UTC, lmchaves commented on src/pedido.py
> +            sede_optima = min(opciones, key=lambda x: x[1])
ya lo he cambiado [6601616](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/66016166b8cd4c3ae31f3de193a2fc6bfe4ec709)

2025-01-10 17:54 UTC, lmchaves commented on src/pedido.py
> +            if pieza in sede.inventario and sede.inventario[pieza][0] >= cantidad_requerida:
lo he cambiado para que sea mas limpio y facil de entender y no tanto for e if anidado: [6601616](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/66016166b8cd4c3ae31f3de193a2fc6bfe4ec709)

2025-01-10 17:55 UTC, lmchaves commented
@JJ ya he realizdo los cambios y he modificado errores que cometia en los tests

2025-01-13 13:11 UTC, JJ reviewed
Por favor, mira los [errores comunes](https://github.com/JJ/IV-/blob/master/errores/objetivo-4.md):

> 

Los issues deben plantear problemas, igual que en el objetivo 2. El código resuelve el problema, y para ver si se ha resuelto, deben usarse los tests.

>    Un issue no puede ser "hacer tests"
>    No se puede plantear "escribir código que haga esto" como issue. Debe plantearse el problema que debe resolverse.

2025-01-13 13:11 UTC, JJ commented on docs/test_runner.md
> +2. **Funcionalidades integradas:** Se valoran las herramientas que incluyan funcionalidades necesarias para las pruebas, evitando dependencias adicionales. Esto reduce la necesidad de instalar comple
De veras que debéis leer lo que escribís. ¿Hay alguna herramienta que *no* las incluya? ¿De veras es esto lo que quieres decir? ¿Que las herramientas de test incluyan funcionalidades necesarias para hacer tests?

2025-01-13 13:11 UTC, JJ commented on docs/test_runner.md
> +2. **Funcionalidades integradas:** Se valoran las herramientas que incluyan una biblioteca de aserciones integrada y otras funcionalidades necesarias para las pruebas, evitando dependencias adicional
Al menos lo has corregido, pero ¿estás diciendo que se valorará que las bibliotecas de aserciones incluyan una biblioteca de aserciones?

2025-01-13 13:11 UTC, JJ commented on src/pedido.py
> +def realizar_pedido(sede_origen, sede_destino, piezas_requeridas, distancia):
Por favor, sigue la regla de los 50 caracteres en la primera línea del mensaje de commit.

2025-01-13 13:11 UTC, JJ commented on README.md
> +make check
No se resuelve *nunca* sin ningún cambio. Y eso en el objetivo 4 deberíais saberlo ya.

2025-01-13 16:22 UTC, lmchaves commented on docs/test_runner.md
> +2. **Funcionalidades integradas:** Se valoran las herramientas que incluyan una biblioteca de aserciones integrada y otras funcionalidades necesarias para las pruebas, evitando dependencias adicional
Ya he dejado calro el cirterio [e946f51](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/e946f51b81ae7cc200a81b5f1d6bc6fb0dc9c330)

2025-01-13 16:22 UTC, lmchaves commented
@JJ como el #24 he mezclado tanto la selección de herramienta como el código, he creado el #26, pero tengo una duda, elimino los archivos de codigo y los vuelvo a poner para tener en #26 los menasjes de commit explicando el código? yaque njo lo he hecho bien

2025-01-14 11:46 UTC, JJ commented
> @JJ como el #24 he mezclado tanto la selección de herramienta como el código, he creado el #26, pero tengo una duda, elimino los archivos de codigo y los vuelvo a poner para tener en #26 los menasjes de commit explicando el código? yaque njo lo he hecho bien

haz lo que estimes conveniente y solicita evaluación cuando lo hagas. Yo no voy a decirte *nunca* lo que tienes que hacer.

2025-01-14 15:13 UTC, lmchaves commented
@JJ ya está listo pra revisión

2025-01-15 16:40 UTC, JJ requested changes
Tienes dos funciones, `realizar_pedido` y `seleccionar_sede_optima` que no tienen nada que ver la una con la otra. En la segunda tienes un pedidos.append pero no usa `realizar_pedido`. ¿Hay algo que me estoy perdiendo aquí? ¿Cuál de las dos es la lógica de negocio?

2025-01-15 16:40 UTC, JJ commented on src/pedido.py
> +
Por favor, no metáis ruido con cambios sin sentido.

2025-01-15 16:40 UTC, JJ commented on src/pedido.py
> +    velcidad= 80
typo. También hay una convención determinada para las constantes. Por favor, averíguala y úsala.

2025-01-15 17:59 UTC, lmchaves commented
@JJ ya lo he cambiado aqui [0a46c6c](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/0a46c6c3ee0e7dfc1ad122f0edfe7fb13563fc2a)

2025-01-17 13:10 UTC, JJ requested changes
Esto no lo había visto antes, pero en infraestructura virtual lo que *nunca* se hace es incluir los datos en el código. Se trata precisamente de montar una infraestructura para que se carguen los datos cuando se necesiten, se arranque el programa o lo que sea.

2025-01-17 13:10 UTC, JJ commented on src/datos_sedes.py
> +script_dir = os.path.dirname(__file__) # Obtiene el directorio del script actual
¿Te parece correcto que un fichero que se llama "datos" se cargue en el *código en producción*?

2025-01-17 13:11 UTC, JJ commented on src/datos_sedes.py
> +import pandas as pd
No se puede usar ninguna biblioteca externa.

2025-01-17 16:57 UTC, lmchaves commented
Ya lo he corregido y ya no cargo ningun dato @JJ

2025-01-18 09:46 UTC, JJ requested changes
No se cierra *nunca* un comentario sin indicar cómo se ha resuelto (o resolviéndolo efectivamente haciendo un cambio)

2025-01-18 09:46 UTC, JJ commented on src/pedido.py
> +
Esto no está resuelto.

2025-01-18 10:31 UTC, lmchaves commented on src/pedido.py
> +
perdón juraría que ya lo habia resuleto, aqui lo modifico [4a593ab](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/4a593ab12737990c71d45b86714cb6a69414a61b)

2025-01-18 10:31 UTC, lmchaves commented
Ya lo he arreglado @JJ

2025-01-18 12:02 UTC, JJ requested changes
Aparte de las buenas prácticas, creo que hay algún problema en el modelo que deberías de reconsiderar. En caso necesario reabre los issues correspondientes, o crea issues nuevos.

2025-01-18 12:02 UTC, JJ commented on src/pedido.py
> +                distancia=mejor_opcion["distancia"],
¿Para qué quieres esto si ya has elegido la mejor opción?

2025-01-18 12:02 UTC, JJ commented on src/pedido.py
> +        tiempo_estimado_llegada=distancia / Pedido.VELOCIDAD,
No recuerdo bien qué tienes en la HU requerida, pero no acabo de ver para qué necesitas esto en lo que es esencialmente un resultado de una función. ¿Haría falta siquiera esta función? Cuando la lógica de negocio produce un resultado, ¿no sería ya eso un producto mínimamente viable? Puede que esto lo necesites más adelante, pero esencialmente lo que tienes que ver es cuál es el PMV que necesitas.
Trabajar con PMVs simplifica mucho al evaluación por parte de los revisores, porque ven estricttamente lo que es necesario y pueden apreciar su calidad más fácilmente.

2025-01-18 12:02 UTC, JJ commented on src/pedido.py
Y realmente si esto es sólo necesario para almacenar el resultado de la lógica de negocio, tendrías que plantearte si *todo* es necesario.

2025-01-18 12:02 UTC, JJ commented on src/sede.py
> +    R = 6371.0
Wait, what? Una cosa es que no haya números mágicos y otra es que llames con un nombre mágico a un número mágico.

2025-01-18 12:02 UTC, JJ commented on src/sede.py
> +            dict | tuple: Si `pieza` es None, devuelve el inventario completo como un diccionario.
Esto no puedes hacerlo NUNCA, usar valores específicos para significar una cosa diferente de lo que son. También incumple el principio de responsabilidad única.

2025-01-18 12:02 UTC, JJ commented on tests/test_pedidos.py
> +        "Motor": (5, 3100),
Esto es problema del modelo, pero realmente el modelo debería de darle nombres específicos a valores específicos. Viendo esto quien revisa no puede saber si lo primero es el precio y lo segundo al cantidad, o al revés.

2025-01-18 19:11 UTC, lmchaves commented on tests/test_pedidos.py
> +        "Motor": (5, 3100),
aqui ya se entiede correctamente [021f75b](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/021f75b44588d5bd5ec2a358cfb3e526e4823664)

2025-01-18 19:12 UTC, lmchaves commented on src/sede.py
> +    R = 6371.0
ya lo he arreglado [0a5e8aa](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/0a5e8aa571b3d9910d08ba7619ef8301a84f10a1)

2025-01-18 19:13 UTC, lmchaves commented on src/pedido.py
Tras pensarlo la verdad es qeu actualmente pedido solo almanceba el resultado, por lo que no hace mas que complicar el entendimiento, aqui lo he modificado [0a5e8aa](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/0a5e8aa571b3d9910d08ba7619ef8301a84f10a1)

2025-01-18 19:14 UTC, lmchaves commented
ya está listo @JJ

2025-01-19 09:07 UTC, JJ requested changes
Todavía hay algunos aspectos que podrías mejorar. Ánimo.

2025-01-19 09:07 UTC, JJ commented on src/sede.py
>          if self.ubicacion_latitude < -90 or self.ubicacion_latitude > 90:
Sigue habiendo números mágicos.

2025-01-19 09:07 UTC, JJ commented on src/sede.py
> +    def tiene_pieza_disponible(self, pieza: str, cantidad_requerida: int) -> bool:
¿El nombre corresponde a lo que hace la función?

2025-01-19 09:07 UTC, JJ commented on src/sede.py
> +        item = self.inventario.get(pieza)
¿Por qué usas `get` en vez de `[ ]`?

2025-01-19 09:07 UTC, JJ commented on src/sede.py
> +            coste_km (float): Costo por kilómetro de transporte. Por defecto es 0.5.
El problema de los comentarios, aunque sean docstrings, es que hay que tratarlos como el código y mantenerlos de la misma manera. Además, si el comentario no se corresponde con el código, *los dos están mal*

2025-01-19 09:07 UTC, JJ commented on src/sede.py
> +        coste_km=0.5
¿Esto está declarado correctamente según las buenas prácticas de Python? ¿Incluyendo el lugar?
Al final, esta función hace una operación. ¿De veras merece la pena tener una función para esto?

2025-01-19 09:07 UTC, JJ commented on src/sede.py
> +            if opciones:
Un if después de un map y un filter... ¿No se podría simplificar? Todo ello dentro de un `for`, además...

2025-01-19 09:07 UTC, JJ commented on src/sede.py
> +                pedidos.append({
¿Te parece que según el principio de la responsabilidad única una función que se llama `seleccionar_sede_óptima` añada a la lista de pedidos?

2025-01-19 11:48 UTC, lmchaves commented on src/sede.py
> +                pedidos.append({
Lo he arreglado [505dc8c](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/505dc8c878b257861b701444a8c7e0ebbd7ee439)

2025-01-19 11:48 UTC, lmchaves commented on src/sede.py
> +            if opciones:
Lo he simplificado [505dc8c](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/505dc8c878b257861b701444a8c7e0ebbd7ee439)

2025-01-19 11:49 UTC, lmchaves commented on src/sede.py
> +        coste_km=0.5
Ya lo he declarado correctamente y he decidido no mantener la función [8b3e4a6](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/8b3e4a63fee06c6727b1d8139d2a0b14cb9cdd7e)

2025-01-19 11:49 UTC, lmchaves commented on src/sede.py
>          if self.ubicacion_latitude < -90 or self.ubicacion_latitude > 90:
Arreglado [8e6d21c](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/8e6d21cb29c38f3bfa9073da629e6250f536ae7a)

2025-01-19 11:49 UTC, lmchaves commented on src/sede.py
> +        item = self.inventario.get(pieza)
Arreglado [8e6d21c](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/8e6d21cb29c38f3bfa9073da629e6250f536ae7a)

2025-01-19 11:49 UTC, lmchaves commented on src/sede.py
> +    def tiene_pieza_disponible(self, pieza: str, cantidad_requerida: int) -> bool:
Aqui ya esta corregido [505dc8c](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/505dc8c878b257861b701444a8c7e0ebbd7ee439)

2025-01-19 11:50 UTC, lmchaves commented
Ya he realizado las correcciones @JJ

2025-01-20 12:30 UTC, JJ requested changes
En general, Luis, trabajas correctamente y sueles tener una actitud positiva con los problemas que te señalan. El problema es que eres reactivo y no ves si los problemas resueltos no causan algún problema adicional, o simplemente has solucionado el problema en un lado e introducido en otro.
Ese es el principal problema, y si eso no hubiera estado ahí, no te habría indicado nada de la modelización del problema. Pero quizás refactorizando para modelizar mejor el dominio del problema puedas llegar a una mejor solución para los flujos de datos que incluyan, esta vez, el seguimiento del principio de responsabilidad única.

2025-01-20 12:30 UTC, JJ commented on src/sede.py
> +        if self.ubicacion_longitude < -Sede.LONGITUD or self.ubicacion_longitude > Sede.LONGITUD:
De veras, Luis, desde el cariño, ¿crees que la longitud y latitud máxima son variables *de sede*?

2025-01-20 12:30 UTC, JJ commented on src/sede.py
> +        a = sin(dlat / 2) ** 2 + cos(radians(self.ubicacion_latitude)) * cos(radians(otra_sede.ubicacion_latitude)) * sin(dlon / 2) ** 2
Las IA generativas tienen la mala costumbre de usar variables sin nombres significativos. No tiene mayor importancia porque esta no es la parte principal de la lógica de negocio, pero de verdad que deberíais usar identificadores con nombres significativos.

2025-01-20 12:30 UTC, JJ commented on src/sede.py
> +            mejor_opcion = Sede.seleccionar_sede_optima(pieza, cantidad, sedes, sede_actual)
Luis, te prometo que tenía la mejor voluntad de dejarte pasar en esta ronda. Pero si tomas una función que no tiene una sola responsabilidad y la divides en dos funciones **una de las cuales hace dos cosas, generar pedidos y otra cosa que no dice  en el nombre, que es seleccionar sede óptima**, es que no has entendido qué es el principio de responsabilidad única. Por favor, trata de entenderlo  y crea un flujo de datos dentro del programa con una serie de funciones que trabajen con los datos *solo de una forma* y que *no tengan efectos secundarios* que los hacen difíciles o imposibles de depurar.

2025-01-20 12:30 UTC, JJ commented on src/sede.py
> +    def generar_pedidos(piezas_requeridas, sedes, sede_actual):
Por otro lado, estás trabajando con funciones estáticas, varias de las cuales reciben como argumento `sede`. Un objeto de una clase es simplemente una colección de funciones en las que uno de los argumentos es siempre el mismo. ¿Puede ser que teniendo varias funciones estáticas (es decir, que no son parte de un objeto) y que además tengan todas un argumento común, `sedes`, lo que esté pidiendo es que trates de modelar esto de una forma un poco más adecuada? ¿Que te permita además incluir un flujo de trabajo con funciones cada una de las cuales tenga una responsabilidad única?

2025-01-21 17:05 UTC, lmchaves commented on src/sede.py
> +        if self.ubicacion_longitude < -Sede.LONGITUD or self.ubicacion_longitude > Sede.LONGITUD:
ya esta solucionado [6d9a167](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/6d9a167ea60d8ff4f9a50b468de85088c848fea6)

2025-01-21 17:05 UTC, lmchaves commented on src/sede.py
> +        a = sin(dlat / 2) ** 2 + cos(radians(self.ubicacion_latitude)) * cos(radians(otra_sede.ubicacion_latitude)) * sin(dlon / 2) ** 2
ya esta arreglado [6d9a167](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/6d9a167ea60d8ff4f9a50b468de85088c848fea6)

2025-01-21 17:07 UTC, lmchaves commented on src/sede.py
> +    def generar_pedidos(piezas_requeridas, sedes, sede_actual):
aqui lo he solucionado [50d2bda](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/50d2bdab8699ea67c8d5ee58366b8b4aee7b2e60)

2025-01-21 17:07 UTC, lmchaves commented on src/sede.py
> +            mejor_opcion = Sede.seleccionar_sede_optima(pieza, cantidad, sedes, sede_actual)
Aqui esta solucionado y ya no forma parte de sede: [62fa512](https://github.com/lmchaves/OrganizarTaller/pull/25/commits/62fa512ec35f4e266e025c6ccaf2fce6e5f90aad)

2025-01-21 17:10 UTC, lmchaves commented
Lo primero @JJ gracias por la paciencia, y he decidido modificar el modelo añadaiendo la entidad gestorPedidos la cual se encarga de la lógica de negocio, para tener así un correcto flujo de datos y cumplir el principio de responsabilidad unica.

2025-01-21 19:00 UTC, JJ approved these changes
Aunque todavía podría mejorar, yo creo que el objetivo está superado.
Por favor, recuerda que las revisiones de compañeros son importantes para los 2 puntos adicionales; aunque no hayas salido aleatoriamente y aunque haya revisado yo ya, mira sobre todo en el objetivo 4 aquellos que estén activos (que hayan solicitado revisión en las últimas dos semanas) y revisa alguno. Puedes verlos en la página donde se entregan los objetivos.

2025-01-21 19:00 UTC, JJ commented on src/pedido.py
No entiendo muy bien. En ese commit borras el fichero, pero sigue apareciendo aquí.

2025-01-21 19:00 UTC, JJ commented on tests/test_pedidos.py
> +    pedido_motor = next((p for p in resultado if p["pieza"] == "Motor"), None)
Aquí podrías aplicar un poco de DRY.

2025-01-21 19:25 UTC, merged