[IV-24-25] Objetivo 1
lmchaves/OrganizarTaller pull request #7
Opened 2024-10-16 16:40 UTC by lmchaves

* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
Sí, cada milestone establece qué funcionalidad se va a implementar, lo que permite empezar a trabajar desde la estructura del taller hasta la implementación de la lógica de negocio.
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
Sí, el Milestone 0 está relacionado con el modelado del dominio, que es el primer paso lógico. A partir de ahí, los milestones avanzan de forma secuencial y lógica.
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
Sí.
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
 M0 establece las bases para poder implementar las historias de usuario
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
Sí, se enfoca en modelar el dominio del problema, lo que es fundamental antes de implementar cualquier lógica de negocio.
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
Sí, se describen claramente los criterios que hacen que el producto sea válido.
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
Son graduales, ya que primero se modela, luego se consulta el inventario y después se gestiona la distribución de piezas entre sedes. Esto evita saltos grandes y permite un avance progresivo.
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
Sí, el Milestone 0 es interno (modelado del sistema), mientras que los siguientes (M1 y M2) son externos, ya que afectan la interacción con usuarios del sistema, como mecánicos y el jefe del taller.
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
Sí.
* [x] ¿El milestone 0 es mínimo *y* viable?
Sí.
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
Sí, cada milestone incluye criterios de viabilidad claros.
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
Sí.
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
Sí, hay coherencia suficiente
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?
Sí, las historias de usuario presentan beneficios claros.

2024-10-17 09:30 UTC, GaelGoncalba commented
Buenas, se me ha asignado revisar tu PR.

2024-10-17 10:10 UTC, GaelGoncalba commented on docs/user-journeys.md
Las necesidades de los usuarios están bien reflejadas, pero te sugiero especificar más cómo es la interacción del usuario con el sistema. Además de describir las necesidades de los clientes podrías añadir los pasos específicos que siguen para conseguir solucionar sus problemas (por ejemplo, el usuario inicia sesión, selecciona una pieza para ver su disponibilidad, el sistema muestra...etc). De esta manera se facilita luego el desarrollo de cada funcionalidad de la aplicación.

2024-10-17 10:10 UTC, GaelGoncalba commented on docs/milestones.md
Creo que los hitos del proyecto están bastante completos y siguen una progresión adecuada, simplemente sugeriría añadir en el documento las historias de usuario asociadas a cada milestone, o añadir un enlace para cada hito a su correspondiente sección en la pestaña Milestones de los Issues, para poder verlo todo más fácilmente.

2024-10-19 17:26 UTC, lmchaves commented on docs/user-journeys.md
Tienes razón en que detallar los pasos específicos que los usuarios seguirán para interactuar con el sistema puede ayudar a aclarar el proceso y minimizar cualquier duda en el futuro. 
Esta corregido aqui: da91d1b

2024-10-19 17:27 UTC, lmchaves commented on docs/milestones.md
Corregido aqui: 5096c8b

2024-10-20 10:09 UTC, GaelGoncalba approved these changes
Por mi parte con esos cambios que has realizado creo que todo está correcto en el objetivo

2024-10-21 14:55 UTC, lmchaves commented
@JJ ha sido aprobado por un compañero, pero el resto que había asignado no han respondido nada, hice el pull request el miércoles pasado

2024-10-21 15:10 UTC, JJ requested changes
Revisa también el resto por si hubiera algún otro error o patrón frecuentemente repetido más.

2024-10-21 15:10 UTC, JJ commented on README.md
> +- Costos de transporte entre sedes.
Estos cambios que no entran en la revisión sólo añaden ruido. Por favor, hacedlos antes del PR y dejad en este solo lo necesario para el objetivo.

2024-10-21 15:10 UTC, JJ commented on docs/README.md
> +# Sistema de Gestión para Taller de Coches
No sé por qué lo has movido aquí. La descripción tiene que estar en el README, y una vez más, sólo debe ir en el PR lo que se vaya a revisar.

2024-10-21 15:10 UTC, JJ commented on docs/README.md
> +Un taller de coches con varias sedes en distintas ciudades de España está enfrentando problemas para gestionar de manera eficiente la distribución y disponibilidad de las piezas necesarias para las r
Además, ¿estás repitiendo lo que pone en el README principal? ¿Por qué razón?

2024-10-21 15:10 UTC, JJ commented on docs/milestones.md
Resuelve si está corregido.

2024-10-21 15:10 UTC, JJ commented on docs/milestones.md
> +- __Objetivo__ : Analizar los diferentes HUs para crear un modelo que represente los elementos del dominio del problema, reflejando la estructura del taller automotriz y los procesos de gestión logís
Por favor, lee [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md) (primer párrafo)

2024-10-21 17:03 UTC, lmchaves commented on README.md
> +- Costos de transporte entre sedes.
Ahora hay alguna manera para que nos salgan estos cambios en este objetivo?

2024-10-21 17:03 UTC, lmchaves commented
He corregido lo del readme en la carpeta docs, y el milestone 0. @JJ

2024-10-21 17:10 UTC, JJ reviewed
También en el mismo fichero de errores se indica:

> Si se entiende cualquier pregunta o comentario que se hace en el PR como "hay que cambiar esto por cualquier otra cosa" no se va a avanzar hacia la consecución del objetivo. Se debe de intentar contestar a las preguntas que se hacen, y si las respuestas no se conocen o no son satisfactorias, se debe simplemente eliminar el texto correspondiente.

Te rogaría que a partir de ahora, si haces cambios digas explícitamente en el mensaje de commit cómo has corregido el error indicado.

2024-10-21 17:10 UTC, JJ commented on README.md
> +- Costos de transporte entre sedes.
Cámbialos en main y haz un rebase o un merge hacia esta rama

2024-10-21 17:10 UTC, JJ commented on docs/milestones.md
> +- __Objetivo__ : Analizar las diferentes Historias de Usuario para identificar los elementos clave que intervienen en el sistema del taller. A partir de este análisis, se desarrollará una representac
No creo que sea la mejor forma de aprovechar el tiempo para ninguno de los dos que no [leas los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md), muevas una frase que no tiene nada que ver con el error señalado, y me pidas revisión de nuevo. Tanto el original como el actual tienen errores, que además son frecuentes y están explícitamente escritos en ese fichero de errores.

2024-10-21 17:26 UTC, lmchaves commented
Si perdón, aqui estan los cambios: el del Readme 5ef0619 y del milestone 0 dc6ce92

2024-10-22 14:07 UTC, lmchaves commented
Esta aquí corregido: 3c1c643 @JJ

2024-10-22 15:10 UTC, JJ commented
> si haces cambios digas explícitamente en el mensaje de commit cómo has corregido el error indicado.

¿Crees que "update milestones.md" explica de alguna forma cómo has corregido los errores que te he indicado o que has visto en errores frecuentes?

2024-10-22 16:30 UTC, lmchaves commented
En este nuevo commit: 96c82a4, he explicado los diferentes cambios del commit 3c1c643, que no había explicado anteriormente @JJ

2024-10-22 17:53 UTC, JJ reviewed
En ningún momento te dije que "modelo del problema" era un error. Tanto "modelo del problema" como "dominio del problema" como "estructura del problema" son un error si no son consecuencia de entender lo que se está haciendo en este objetivo y para qué sirve un milestone/PMV sino un simple intento de "quitarse este objetivo de en medio"

Te aconsejaría que leyeras de nuevo [el guión](https://jj.github.io/IV/documentos/proyecto/1.Infraestructura#informaci%C3%B3n-adicional) y trates de entender de qué se trata aquí y por qué es importante que se haga correctamente. Te lo puedo explicar en clase, que no recuerdo haberlo hecho. En todas las sesiones hago énfasis en la importancia de asistir a clase, para entender las claves y la trascendencia de cada uno de los objetivo y qué es lo que se busca que aprendáis con cada uno de ellos.

2024-10-22 17:53 UTC, JJ commented on README.md
> +- Costos de transporte entre sedes.
Esto sigue aquí. Por favor, elíminalo.

2024-10-22 17:53 UTC, JJ commented on docs/milestones.md
> +    - Código que implemente las entidades principales relacionadas con las HU1 y HU2, incluyendo: Piezas, Inventario, Sedes y Transporte.
Si ya sabes qué entidades hay, ¿para qué necesitas modelizarlo? Ya las tienes ahí.

2024-10-22 17:53 UTC, JJ commented on docs/milestones.md
> +    - El código debe mostrar las relaciones entre estas entidades, como la interacción entre inventario y sedes, el flujo de piezas entre sedes, y cómo los tiempos de transporte afectan la disponibil
¿Estas "relaciones" son parte del dominio?

2024-10-22 17:53 UTC, JJ commented on docs/milestones.md
> +Se considerará completado cuando el código refleje correctamente las interacciones del dominio descrito en las HU1 y HU2.
Cuando una persona trabaje en tu objetivo 2 y te entregue un código, ¿cómo vas a comprobar estas interacciones del "dominio"?

2024-10-22 17:53 UTC, JJ commented on docs/milestones.md
> +# [ [M2] Milestone 2:  Implementación de pedidos de piezas](https://github.com/lmchaves/OrganizarTaller/milestone/3)
¿Has leído la parte del [fichero de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md) donde pone:

> 

    En desarrollo ágil más allá de dos milestones por delante no tiene mucho sentido planificar. Pero si se hace, conviene que se mire la progresión de objetivos de la asignatura para que se ajusten, en lo posible, a lo que se encuentra ahí.

2024-10-25 13:22 UTC, lmchaves commented on docs/milestones.md
> +# [ [M2] Milestone 2:  Implementación de pedidos de piezas](https://github.com/lmchaves/OrganizarTaller/milestone/3)
No se muy bien, como cambiar este milestone, ya que trata sobre uno uno de los probelmas mas importantes, dentro de mi problema global, que es, que cuando pides una pieza, tienes que tener en cuenta en que sede está esa peiza, teniendo en cuenta el coste y tiempo.

Luego lo de prioridad sobre los clientes en un principio lo pensé para otro milestone.

2024-10-25 13:23 UTC, lmchaves commented
He corregido el milestone 0: [c4c5b87](https://github.com/lmchaves/OrganizarTaller/pull/7/commits/c4c5b87ef65da287f528b19e33434223f03649c8) @JJ

2024-10-28 06:14 UTC, JJ commented on docs/milestones.md
> +# [ [M2] Milestone 2:  Implementación de pedidos de piezas](https://github.com/lmchaves/OrganizarTaller/milestone/3)
Si es tan importante, ¿por qué lo dejas para el 2?

2024-10-28 06:15 UTC, JJ requested changes
Tienes que resolver todos los comentarios.

2024-10-28 06:15 UTC, JJ commented on README.md
> +>>>>>>> 8141f43 (Aplicar cambios que no forman parte del objetivo actual)
Estás dejando marcas de conflicto de fusión.

2024-10-28 10:01 UTC, lmchaves commented on docs/milestones.md
> +# [ [M2] Milestone 2:  Implementación de pedidos de piezas](https://github.com/lmchaves/OrganizarTaller/milestone/3)
He organizado los milestones en esta secuencia para asegurar una progresión adecuada y la consulta de disponibilidad de piezas en el Milestone 1 es una funcionalidad más básica y manejable para iniciar el desarrollo y probar el sistema, mientras que el Milestone 2, que abarca la implementación de pedidos entre sedes con factores como costos de transporte y tiempos de entrega, es más complejo e introduce lógica adicional de optimización.

Pero si esto supone que la realización de los milestones es errónea, cambiaré el orden de dichos milestones.

2024-10-28 10:06 UTC, JJ commented on docs/milestones.md
> +# [ [M2] Milestone 2:  Implementación de pedidos de piezas](https://github.com/lmchaves/OrganizarTaller/milestone/3)
Sólo puedo repetirte lo que he puesto al principio. A partir de ahí, la secuencia debe responder a los intereses del cliente, y también al hecho de que si en el milestone 1 no se incluye una lógica de negocio suficiente no se podrá llevar a cabo el objetivo 4 de la asignatura.

2024-10-28 11:22 UTC, lmchaves commented
Revisión [d4656ff](https://github.com/lmchaves/OrganizarTaller/pull/7/commits/d4656ffdd1d1a80e8f1decdd6b5786c5480a0dde) @JJ

2024-10-29 12:11 UTC, JJ requested changes
Por favor, tratad de entender correctamente 
1. Qué es un PMV
2. Qué importancia tiene el primer PMV
3. Qué relación hay entre los PMVs y las historias de usuario.

Y, en general, para qué sirve todo esto y por qué diablos insisto en pediros esto en esta asignatura.

2024-10-29 12:11 UTC, JJ commented on docs/README.md
Ya os he repetido que sólo deben aparecer aquí los ficheros que se revisen. Si queréis borrar o cambiar algo, hacedlo en main, por favor, y luego rebase.

2024-10-29 12:11 UTC, JJ commented on docs/milestones.md
> +- Hay que realizar un modelo inicial sobre el dominio del problema, explicado en las historias de usuario [HU1](https://github.com/lmchaves/OrganizarTaller/issues/4) y [HU2](https://github.com/lmchav
¿Puedes poner un ejemplo de una "relación entre entidades"?
En todo caso, ¿esta frase añade información sobre el "modelado del problema" o el "modelo inicial *sobre* el dominio del problema"? ¿Las dos cosas son lo mismo? ¿Hay que modelar "el problema" o "sobre el dominio del problema"? ¿Las entidades y relaciones son exactamente qué? ¿El modelo inicial? ¿El dominio del problema? ¿Ninguna de las  dos cosas?

2024-10-29 12:11 UTC, JJ commented on docs/milestones.md
> +    - Código de las entidades definidas.
¿Qué entidades? ¿El PMV es "entidades"?

2024-10-29 12:11 UTC, JJ commented on docs/milestones.md
> +Se considerará completado cuando el código refleje correctamente el dominio del problema descrito en las [HU1](https://github.com/lmchaves/OrganizarTaller/issues/4) y [HU2](https://github.com/lmchave
Entonces el "modelo inicial" ¿qué es? 
Por otro lado, ¿divides el problema en dos historias de usuario pero luego se trabaja en las dos a la vez? ¿Por qué razón?

2024-10-29 12:11 UTC, JJ commented on docs/milestones.md
> +- IImplementar la funcionalidad que permita a Javier, el mecánico, consultar la disponibilidad de piezas en el sistema. La información incluirá si la pieza está disponible en el taller local y, en ca
Pone "II". 
¿Estás diciendo ya qué hay que implementar? ¿Para qué quieres las entidades entonces (o el modelo, o el modelo sobre el dominio?

2024-10-29 12:11 UTC, JJ commented on docs/milestones.md
> +    - Código que implemente la consulta de disponibilidad de piezas en el inventario, junto con los tiempos estimados de entrega.
¿Ya sabes lo que va a implementar? ¿Para qué sirven las historias de usuario entonces?

2024-10-30 17:28 UTC, merged

2024-10-30 18:57 UTC, JJ commented
Has cerrado accidentamente el PR, ¿no?

2024-10-31 10:59 UTC, lmchaves commented
Si, accidentalmente, cerré el pull request asociado al objetivo1. Fue un error de manipulación mientras trabajaba en la rama, y ya estoy en proceso de solucionarlo para asegurar que los cambios necesarios puedan revisarse.

He creado un nuevo pull request para continuar con el flujo de revisión sin problemas. Aprecio su comprensión y lamento las molestias causadas.

Este es el enlace https://github.com/lmchaves/OrganizarTaller/pull/8/ , no se como cambiar en el archivo de enlaces, sin tener que realizar un pull request y se me asigne de nuevo 5 revisores.

2024-10-31 11:01 UTC, JJ commented
Igual no vendría mal pasar por esa segunda ronda de revisores. Lo que tú veas.

2024-10-31 12:31 UTC, lmchaves commented
Vale pues lo envío.